#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-techspike-customer-registry-core [OPTION...]
    Open customer registry in VS Code.

    Options:
      -f, --functions   include Azure Function Apps
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -f|--functions)
      functions="true"
      ;;
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
  code ./ffc-techspike-customer-registry;
  code ./ffc-techspike-customer-web;
  code ./ffc-techspike-customer-registry-data-consumer;
  code ./ffc-techspike-customer-registry-event;
  code ./ffc-techspike-customer-registry-alert;
