#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-pay$ --format={{.Name}})" ]; then
  echo "Creating ffc-techspike Docker network"
  docker network create ffc-pay
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-techspike-customer-registry-core [OPTION...]
    Run customer registry services.

    Options:
      -f, --functions   include Azure Function Apps
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
     -f|--functions)
      functions="true"
      ;;
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
  ./ffc-techspike-customer-registry/scripts/start -d;
  ./ffc-techspike-customer-web/scripts/start -d;
  ./ffc-techspike-customer-registry-data-consumer/scripts/start -d;
  ./ffc-techspike-customer-registry-event/scripts/start -d;
  ./ffc-techspike-customer-registry-alert/scripts/start -d;
