#!/usr/bin/env sh
set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

show_help() {
  echo "
    Usage: path/to/ffc-techspike-customer-registry-core [OPTION...]
    Update customer registry services.

    Options:
      -h, --help       display this help text
    "
}

while :; do
  case $1 in
    -h|--help)   # Call a "show_help" function to display a synopsis, then exit.
      show_help
      exit
      ;;
    *)
      break
  esac

  shift
done

cd "${projectRoot}"
cd ./ffc-techspike-customer-registry && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-techspike-customer-web && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-techspike-customer-registry-data-consumer && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-techspike-customer-registry-event && \
  git checkout main && \
  git pull
cd "${projectRoot}"
cd ./ffc-techspike-customer-registry-alert && \
  git checkout main && \
  git pull